import type { Metadata } from "next";
import MarketingShell from "@/components/MarketingShell";
import ExamplesContent from "@/components/ExamplesContent";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://litstatus.com";

export const metadata: Metadata = {
  title: "Caption Examples - Real AI Generated Outputs",
  description:
    "Explore real caption examples generated by LitStatus AI. See Standard, Savage, and Rizz mode outputs for Instagram, TikTok, and social media with hashtags.",
  keywords: [
    "caption examples",
    "instagram caption examples",
    "tiktok caption examples",
    "ai generated captions",
    "caption inspiration",
    "social media caption ideas",
    "rizz caption examples",
    "savage caption examples",
  ],
  openGraph: {
    title: "Caption Examples - Real AI Generated Outputs | LitStatus",
    description:
      "Explore real caption examples generated by LitStatus AI. See Standard, Savage, and Rizz mode outputs for Instagram, TikTok, and social media.",
    url: `${SITE_URL}/examples`,
    type: "website",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "LitStatus Caption Examples",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Caption Examples - Real AI Generated Outputs | LitStatus",
    description:
      "Explore real caption examples generated by LitStatus AI. See Standard, Savage, and Rizz mode outputs.",
  },
  alternates: {
    canonical: "/examples",
  },
};

export default function ExamplesPage() {
  return (
    <MarketingShell
      title={{ en: "Examples", zh: "示例" }}
      subtitle={{
        en: "Real outputs across modes, ready to copy.",
        zh: "覆盖多种语气的真实示例。",
      }}
    >
      <ExamplesContent />
    </MarketingShell>
  );
}
